### PR TITLE
fix: server is not started when game is save is locked

### LINKED ISSUE #29: Server launches even if save is locked
Waiting for action command (run, load, save, exit):
run
2024-08-05 20:33:51.8978|INFO|BuddySave|Game save is locked, your friends are playing!
2024-08-05 20:33:51.9373|INFO|BuddySave|Server started, waiting for exit: "C:\Program Files (x86)\Steam\steamapps\common\Valheim dedicated server\start_headless_server.bat"

### PR DESCRIPTION
**Pull request by lightTAKE**
Added `OrchestratorResult` that is returned from `SharedSaveOrchestrator.Load()` with values `Failed`/`Loaded`/`SaveLocked`;

I thought about solutions: 

- Move `ILockManager` to `GamingSession`. But I didn't want to duplicate the usage of `LockManager` methods as I think it's important for `SharedSaveOrchestrator` to use it as it is the one that does the actual loading/saving;
- Throw exception when save is locked in `SharedSaveOrchestrator`. But then I would have to add `try`/`catch` blocks, which would be an ugly implementation IMO;
- This solution with `OrchestratorResult`. I think this one fits best as `GameSession` now can check what result from `Load()` method and just return when the result is not that of expected.

Also - I haven't added `OrchestratorResult` to `Save()` method, because I couldn't come up with a use case ATM.

closes #29

### CODE REVIEW

File: BuddySave.UnitTests/Core/GamingSessionTests.cs [hunk 1]
```diff
@@ -55,6 +55,28 @@ public async Task Run_DoesNotStartTheServer_WhenLoadingSaveFails(
         processProviderMock.Verify(x => x.Start(It.IsAny<ProcessStartInfo>()), Times.Never());
     }
 
+    [Theory]
```
Comment (lightTAKE) [inline BuddySave.UnitTests/Core/GamingSessionTests.cs:58]: Will add additional test to check if `Save()` is not called.

Comment (lightTAKE) [reply BuddySave.UnitTests/Core/GamingSessionTests.cs:58]: Added two, if you prefer one test for this, let me know. :)

**Review by SparrowBrain — APPROVED** [review]
